// tools/build-wmm.mjs — regenerate js/wmmcof.js from tools/WMM2025.COF.
// Dev-only; run once per model release (next: WMM2030, late 2029).
// The COF file is US-government public domain (NOAA/NCEI + British Geological Survey).
import { readFileSync, writeFileSync } from 'node:fs';

const lines = readFileSync(new URL('./WMM2025.COF', import.meta.url), 'utf8')
  .split('\n').map((l) => l.trim()).filter(Boolean);
const epoch = parseFloat(lines[0].split(/\s+/)[0]);
const terms = [];
for (let i = 1; i < lines.length; i++) {
  const f = lines[i].split(/\s+/).map(Number);
  if (f.length < 6 || !Number.isFinite(f[0]) || f[0] > 12) continue; // skip 999... terminator
  terms.push([f[0], f[1], f[2], f[3], f[4], f[5]]);
}
if (terms.length !== 90) throw new Error(`expected 90 terms, got ${terms.length}`);

const out = `// js/wmmcof.js — GENERATED by tools/build-wmm.mjs from tools/WMM2025.COF.
// World Magnetic Model ${epoch} Gauss coefficients (NOAA/NCEI + BGS, public
// domain). Valid ${epoch}.0–${epoch + 5}.0. Do not edit by hand.
export const WMM_EPOCH = ${epoch};
export const WMM_TERMS = [
${terms.map((t) => `  [${t.join(', ')}],`).join('\n')}
];
`;
writeFileSync(new URL('../js/wmmcof.js', import.meta.url), out);
console.log(`js/wmmcof.js: epoch ${epoch}, ${terms.length} terms`);
